name: Docker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{ steps.image_id.outputs.id }}
    steps:
      - name: Generate Image ID
        id: image_id
        run: echo "::set-output name=id::$(uuidgen)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build dev image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile
          tags: ttl.sh/${{ steps.image_id.outputs.id }}:4h
          target: development
          cache-from: type=gha
          cache-to: type=gha,mode=max

  sqlite-test:
    runs-on: ubuntu-latest
    needs: [build-dev]
    container:
      image: ttl.sh/${{ needs.build-dev.outputs.image_id }}
    steps:
      - run: yarn run test

  sqlite-e2e:
    runs-on: ubuntu-latest
    needs: [build-dev]
    container:
      image: ttl.sh/${{ needs.build-dev.outputs.image_id }}
    steps:
      - run: yarn run test:e2e

  build-prod:
    runs-on: ubuntu-latest
    needs: [sqlite-test, sqlite-e2e]
    steps:
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/davidmehren/hedgedoc
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
